correspondances = {
    "independent" : "i",
    "linear" : "l",
    "cross" : "cr",
    "doublelinear" : "dl",
    "hourglass" : "ho",
    "hypercube" : "hc",
    "hypercubegraph" : "hcg",
    "hypersphere" : "hs",
    "parabola2" : "p2",
    "sine" : "si",
    "star" : "st",
    "zinv" : "zi",
    "linearperiodic": "lp",
}